# Generated by Django 2.1.7 on 2019-03-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sectorwise',
            fields=[
                ('symbol', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('sector', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='stock_data',
            fields=[
                ('ids', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=128)),
                ('date', models.CharField(max_length=128)),
                ('open', models.FloatField(default=0)),
                ('high', models.FloatField(default=0)),
                ('low', models.FloatField(default=0)),
                ('close', models.FloatField(default=0)),
                ('volume', models.FloatField(default=0)),
                ('adj_close', models.FloatField(default=0)),
                ('volume_delta', models.FloatField(default=0)),
                ('cr', models.FloatField(default=0)),
                ('so', models.FloatField(default=0)),
                ('sma', models.FloatField(default=0)),
                ('ema', models.FloatField(default=0)),
                ('macd', models.FloatField(default=0)),
                ('boll', models.FloatField(default=0)),
                ('boll_ub', models.FloatField(default=0)),
                ('boll_lb', models.FloatField(default=0)),
                ('rsi', models.FloatField(default=0)),
                ('tr', models.FloatField(default=0)),
                ('atr', models.FloatField(default=0)),
                ('dma', models.FloatField(default=0)),
                ('trix', models.FloatField(default=0)),
                ('vr', models.FloatField(default=0)),
                ('wr', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('stocks', models.TextField(blank=True)),
            ],
        ),
    ]
