# Generated by Django 2.1.7 on 2019-03-31 21:07

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('FinPro', '0002_auto_20190331_1605'),
    ]

    operations = [
        migrations.AddField(model_name = 'StockData', name = 'timestamp', field = models.IntegerField(default = 0))
    ]
