# Generated by Django 2.1.7 on 2019-04-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinPro', '0003_auto_20190331_1707'),
    ]

    operations = [
        migrations.AddField(model_name = 'UserInfo', name = 'email', field = models.CharField(max_length = 20)),
        migrations.AddField(model_name = 'UserInfo', name = 'age', field = models.IntegerField(default = 0)),
        migrations.AddField(model_name = 'UserInfo', name = 'password', field = models.CharField(blank = True, max_length = 30))
    ]
